version: '3'
services:
  postgres:
    image: postgres:16.1-alpine
    container_name: avatar-postgres
    environment:
      POSTGRES_DB: ${PGSQL_DATABASE}
      POSTGRES_USER: ${PGSQL_USERNAME}
      POSTGRES_PASSWORD: ${PGSQL_PASSWORD}
    volumes:
      - avatar_db:/var/lib/postgresql/data
    ports:
      - ${PGSQL_PORT}:5432
    restart: unless-stopped
    networks:
      - backend_internal

  redis:
    container_name: avatar-redis
    image: redis:7-alpine
    volumes:
      - avatar_redisdata:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    ports:
      - ${REDIS_PORT}:6379
    networks:
      - backend_internal
    restart: unless-stopped

volumes:
  avatar_db:
  avatar_redisdata:

networks:
  backend_internal:
    driver: bridge
